sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
#  alioss:
#    endpoint: sky-itcast-1330413135.cos.ap-nanjing.myqcloud.com
#    access-key-id: LTAI5tPeFLzsPPT8gG3LPW64
#    access-key-secret: U6k1br0Z8gaOIXv3nXbulGTUzy6Pd7
#    bucket-name: sky-itcast
  cos:
    baseUrl: sky-itcast-1330413135.cos.ap-nanjing.myqcloud.com
    accessKey: AKID00yfAQUO4VrzsXyB9tVv87sSpzuiIdjb
    secretKey: hBSVKhtsdAZkgOr61nLyObQAg181pPk4
    regionName: ap-nanjing
    bucketName: sky-itcast-1330413135
    folderPrefix: /files